#!/bin/sh
PREREQ=""
prereqs()
{
	echo "$PREREQ"
}

case $1 in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions
# Begin real processing below this line
config_dir="/etc/rapiddisk"
for i in "${config_dir}"/rapiddisk_kernel_*
	do
		if [ "${config_dir}/rapiddisk_kernel_${version}" = "$i" ] ; then
			size="$(head -n 1 "$i")"
			device="$(head -n 2 "$i" | tail -n 1)"
			cache_mode="$(tail -n 1 "$i")"
			cwd="$(dirname "$0")"
			cp "${config_dir}/rapiddisk_sub.orig" "${cwd}/rapiddisk_sub"
			sed -i 's,RAMDISKSIZE,'"$size"',g' "${cwd}/rapiddisk_sub"
			sed -i 's,BOOTDEVICE,'"$device"',g' "${cwd}/rapiddisk_sub"
			sed -i 's,CACHEMODE,'"$cache_mode"',g' "${cwd}/rapiddisk_sub"
			chmod +x "${cwd}/rapiddisk_sub"
			manual_add_modules rapiddisk
			manual_add_modules rapiddisk-cache
			if [ "$cache_mode" = "wb" ] ; then
				manual_add_modules dm-writecache
			fi
			copy_exec /sbin/rapiddisk /sbin/rapiddisk
			copy_file binary "${cwd}/rapiddisk_sub" /sbin/
			rm "${cwd}/rapiddisk_sub"
			break 2
		fi
	done

exit 0
